export const roomsData = [
  {
    slug: "premier-room",
    name: "Premier Room",
    subtitle: "Comfort Redefined",
    tag: "Popular",
    description: "Experience elegance in our beautifully designed Premier Room. Featuring modern amenities, plush bedding, and stunning city views, this room is perfect for both business and leisure travelers. Every detail has been thoughtfully curated to ensure your comfort.",
    longDescription: "The Premier Room at The Azura offers a perfect blend of comfort and style. Wake up to breathtaking city views through floor-to-ceiling windows, unwind in the plush king-size bed with premium linens, and enjoy the convenience of modern amenities designed for the contemporary traveler.",
    image: "/images/room1.avif",
    gallery: ["/images/rooms/room-1.avif", "/images/room1.avif", "/images/room2.avif"],
    price: "7,500",
    floor: "3rd - 5th Floor",
    bed: "1 King Bed",
    maxGuests: "2 Adults",
    size: "320 sq ft",
    stars: 4,
    amenities: [
      { icon: "Wifi", label: "Free High-Speed Wi-Fi" },
      { icon: "Tv", label: "42-inch LED TV" },
      { icon: "Wind", label: "Central Air Conditioning" },
      { icon: "Coffee", label: "Mini Bar" },
      { icon: "Utensils", label: "Room Service (24/7)" },
      { icon: "Bath", label: "Rain Shower" },
      { icon: "Sparkles", label: "Daily Housekeeping" },
      { icon: "Lock", label: "In-Room Safe" },
    ],
    highlights: ["City View", "Premium Linens", "Blackout Curtains", "Work Desk"],
  },
  {
    slug: "superior-deluxe-room",
    name: "Superior Deluxe Room",
    subtitle: "Spacious Luxury",
    tag: "Best Seller",
    description: "Our Superior Deluxe Room offers extra space and premium finishes. Enjoy the separate seating area, upgraded bathroom, and panoramic views that make your stay truly memorable.",
    longDescription: "Step into the Superior Deluxe Room and feel the difference. With 400 sq ft of thoughtfully designed space, a separate seating area for relaxation, and an upgraded bathroom with luxury toiletries, this room elevates your stay to new heights. Panoramic windows flood the room with natural light.",
    image: "/images/room2.avif",
    gallery: ["/images/rooms/room-2.avif", "/images/room3.avif", "/images/room1.avif"],
    price: "9,500",
    floor: "4th - 6th Floor",
    bed: "1 King Bed",
    maxGuests: "2 Adults",
    size: "400 sq ft",
    stars: 4,
    amenities: [
      { icon: "Wifi", label: "Free High-Speed Wi-Fi" },
      { icon: "Tv", label: "50-inch Smart TV" },
      { icon: "Wind", label: "Central Air Conditioning" },
      { icon: "Coffee", label: "Mini Bar" },
      { icon: "Utensils", label: "Room Service (24/7)" },
      { icon: "Bath", label: "Rain Shower & Bathtub" },
      { icon: "Sparkles", label: "Daily Housekeeping" },
      { icon: "Lock", label: "In-Room Safe" },
    ],
    highlights: ["Panoramic View", "Seating Area", "Upgraded Bathroom", "Nespresso Machine"],
  },
  {
    slug: "executive-room",
    name: "Executive Room",
    subtitle: "Business Class Comfort",
    tag: "",
    description: "Designed for the discerning business traveler, the Executive Room combines functionality with luxury. Features a work desk, ergonomic chair, and premium connectivity.",
    longDescription: "The Executive Room is your personal workspace and retreat. Equipped with a spacious work desk, ergonomic chair, high-speed internet, and premium connectivity options, it is designed to keep you productive. After work, relax in the elegantly appointed living space.",
    image: "/images/room3.avif",
    gallery: ["/images/rooms/room-3.avif", "/images/room1.avif", "/images/rooms/room-2.avif"],
    price: "11,000",
    floor: "6th - 8th Floor",
    bed: "1 King Bed / Twin Beds",
    maxGuests: "2 Adults",
    size: "450 sq ft",
    stars: 4,
    amenities: [
      { icon: "Wifi", label: "High-Speed Wi-Fi" },
      { icon: "Tv", label: "55-inch Smart TV" },
      { icon: "Wind", label: "Central Air Conditioning" },
      { icon: "Coffee", label: "Nespresso Machine" },
      { icon: "Utensils", label: "Room Service (24/7)" },
      { icon: "Bath", label: "Rain Shower" },
      { icon: "Sparkles", label: "Daily Housekeeping" },
      { icon: "Lock", label: "In-Room Safe" },
    ],
    highlights: ["Work Desk", "Ergonomic Chair", "High-Speed Internet", "USB Charging"],
  },
  {
    slug: "presidential-suite",
    name: "Presidential Suite",
    subtitle: "Ultimate Prestige",
    tag: "Luxury",
    description: "The pinnacle of luxury at The Azura. Our Presidential Suite features a private living room, dining area, panoramic terrace, and dedicated butler service for the most discerning guests.",
    longDescription: "The Presidential Suite represents the finest in luxury accommodation. Spanning 1200 sq ft of exquisitely designed space, it includes a private living room with designer furniture, a formal dining area for six, a panoramic terrace with stunning views, and a private jacuzzi. A dedicated butler is at your service around the clock.",
    image: "/images/rooms/room-4.avif",
    gallery: ["/images/rooms/room-4.avif", "/images/rooms/room-5.avif", "/images/room3.avif"],
    price: "35,000",
    floor: "8th Floor",
    bed: "1 King Bed",
    maxGuests: "3 Adults",
    size: "1200 sq ft",
    stars: 5,
    amenities: [
      { icon: "Wifi", label: "Premium Wi-Fi" },
      { icon: "Tv", label: "65-inch OLED TV" },
      { icon: "Wind", label: "Zoned Climate Control" },
      { icon: "Coffee", label: "Full Private Bar" },
      { icon: "Utensils", label: "Private Dining" },
      { icon: "Bath", label: "Private Jacuzzi" },
      { icon: "Sparkles", label: "Butler Service 24/7" },
      { icon: "Lock", label: "Private Terrace" },
    ],
    highlights: ["Panoramic Terrace", "Private Jacuzzi", "Butler Service", "Dining Area"],
  },
  {
    slug: "premier-suite",
    name: "Premier Suite",
    subtitle: "Elegant Living",
    tag: "Family",
    description: "A generous suite with separate living and sleeping areas. Perfect for extended stays or families, the Premier Suite offers home-like comfort with hotel luxury.",
    longDescription: "The Premier Suite is designed for those who appreciate space and elegance. With a separate living room, dining area, and a generously sized bedroom, it provides all the comforts of home with the luxury of a five-star hotel. Sea views from every window make this suite truly special.",
    image: "/images/room2.avif",
    gallery: ["/images/room2.avif", "/images/rooms/room-4.avif", "/images/room1.avif"],
    price: "18,000",
    floor: "7th Floor",
    bed: "1 King Bed",
    maxGuests: "3 Adults",
    size: "750 sq ft",
    stars: 5,
    amenities: [
      { icon: "Wifi", label: "Free High-Speed Wi-Fi" },
      { icon: "Tv", label: "55-inch Smart TV" },
      { icon: "Wind", label: "Central Air Conditioning" },
      { icon: "Coffee", label: "Mini Bar" },
      { icon: "Utensils", label: "Room Service (24/7)" },
      { icon: "Bath", label: "Rain Shower & Bathtub" },
      { icon: "Sparkles", label: "Daily Housekeeping" },
      { icon: "Lock", label: "Sea View" },
    ],
    highlights: ["Sea View", "Separate Living Room", "Dining Area", "Premium Toiletries"],
  },
  {
    slug: "honeymoon-suite",
    name: "Honeymoon Suite",
    subtitle: "Romantic Escape",
    tag: "Romantic",
    description: "Crafted for love and celebration. Our Honeymoon Suite features a king-size bed with premium linens, rose petal turndown service, champagne on arrival, and breathtaking sunset views.",
    longDescription: "The Honeymoon Suite is where romance meets luxury. Every detail is designed to create unforgettable moments — from the rose petal turndown service to the champagne on arrival, from the king-size bed draped in the finest linens to the private balcony with breathtaking sunset views. Celebrate your love in the most beautiful setting.",
    image: "/images/room1.avif",
    gallery: ["/images/room1.avif", "/images/rooms/room-5.avif", "/images/room3.avif"],
    price: "22,000",
    floor: "7th Floor",
    bed: "1 King Bed",
    maxGuests: "2 Adults",
    size: "650 sq ft",
    stars: 5,
    amenities: [
      { icon: "Wifi", label: "Free High-Speed Wi-Fi" },
      { icon: "Tv", label: "50-inch Smart TV" },
      { icon: "Wind", label: "Central Air Conditioning" },
      { icon: "Coffee", label: "Full Bar" },
      { icon: "Utensils", label: "Room Service (24/7)" },
      { icon: "Bath", label: "Freestanding Bathtub" },
      { icon: "Sparkles", label: "Rose Petal Turndown" },
      { icon: "Lock", label: "Sunset View Balcony" },
    ],
    highlights: ["Sunset View", "Champagne on Arrival", "Rose Turndown", "Freestanding Bathtub"],
  },
  {
    slug: "premier-suite-twin",
    name: "Premier Suite Twin",
    subtitle: "Elegant Living — Twin Beds",
    tag: "Family",
    description: "The Premier Suite Twin offers the same generous space and luxury as the Premier Suite, but with twin beds — ideal for friends or colleagues traveling together.",
    longDescription: "Enjoy the elegance and spaciousness of the Premier Suite with the added flexibility of twin beds. The Premier Suite Twin features a separate living room, dining area, and two comfortable twin beds with premium linens. Perfect for friends, colleagues, or family members who prefer separate sleeping arrangements without compromising on luxury.",
    image: "/images/rooms/room-5.avif",
    gallery: ["/images/rooms/room-5.avif", "/images/room2.avif", "/images/rooms/room-4.avif"],
    price: "18,000",
    floor: "7th Floor",
    bed: "2 Twin Beds",
    maxGuests: "2 Adults",
    size: "750 sq ft",
    stars: 5,
    amenities: [
      { icon: "Wifi", label: "Free High-Speed Wi-Fi" },
      { icon: "Tv", label: "55-inch Smart TV" },
      { icon: "Wind", label: "Central Air Conditioning" },
      { icon: "Coffee", label: "Mini Bar" },
      { icon: "Utensils", label: "Room Service (24/7)" },
      { icon: "Bath", label: "Rain Shower & Bathtub" },
      { icon: "Sparkles", label: "Daily Housekeeping" },
      { icon: "Lock", label: "Sea View" },
    ],
    highlights: ["Sea View", "Separate Living Room", "Twin Beds", "Premium Toiletries"],
  },
  {
    slug: "executive-room-double",
    name: "Executive Room (Double)",
    subtitle: "Business Comfort — Double Bed",
    tag: "",
    description: "The Executive Room Double combines business functionality with the comfort of a double bed. Features a work desk, ergonomic chair, and premium connectivity for the professional traveler.",
    longDescription: "Designed for the business traveler who values comfort, the Executive Room Double features a spacious double bed, a dedicated work area with ergonomic chair, high-speed internet, and a Nespresso machine. After a productive day, unwind in the elegantly appointed room with views of the city skyline.",
    image: "/images/room3.avif",
    gallery: ["/images/room3.avif", "/images/room1.avif", "/images/room2.avif"],
    price: "11,000",
    floor: "6th - 8th Floor",
    bed: "1 Double Bed",
    maxGuests: "2 Adults",
    size: "450 sq ft",
    stars: 4,
    amenities: [
      { icon: "Wifi", label: "High-Speed Wi-Fi" },
      { icon: "Tv", label: "55-inch Smart TV" },
      { icon: "Wind", label: "Central Air Conditioning" },
      { icon: "Coffee", label: "Nespresso Machine" },
      { icon: "Utensils", label: "Room Service (24/7)" },
      { icon: "Bath", label: "Rain Shower" },
      { icon: "Sparkles", label: "Daily Housekeeping" },
      { icon: "Lock", label: "In-Room Safe" },
    ],
    highlights: ["Work Desk", "Ergonomic Chair", "Nespresso Machine", "USB Charging"],
  },
  {
    slug: "executive-room-twin",
    name: "Executive Room (Twin)",
    subtitle: "Business Comfort — Twin Beds",
    tag: "",
    description: "The Executive Room Twin offers twin bed configuration with the same business-class amenities. Perfect for colleagues sharing or travelers who prefer separate beds.",
    longDescription: "The Executive Room Twin provides all the business-class amenities of the Executive Room with the added comfort of twin beds. Whether you're traveling with a colleague or simply prefer separate sleeping arrangements, this room ensures a productive and comfortable stay with its dedicated workspace, high-speed connectivity, and premium amenities.",
    image: "/images/room3.avif",
    gallery: ["/images/room3.avif", "/images/room2.avif", "/images/room1.avif"],
    price: "11,000",
    floor: "6th - 8th Floor",
    bed: "2 Twin Beds",
    maxGuests: "2 Adults",
    size: "450 sq ft",
    stars: 4,
    amenities: [
      { icon: "Wifi", label: "High-Speed Wi-Fi" },
      { icon: "Tv", label: "55-inch Smart TV" },
      { icon: "Wind", label: "Central Air Conditioning" },
      { icon: "Coffee", label: "Nespresso Machine" },
      { icon: "Utensils", label: "Room Service (24/7)" },
      { icon: "Bath", label: "Rain Shower" },
      { icon: "Sparkles", label: "Daily Housekeeping" },
      { icon: "Lock", label: "In-Room Safe" },
    ],
    highlights: ["Work Desk", "Twin Beds", "Nespresso Machine", "USB Charging"],
  },
];
